=== knoxsp/Concept/bin/cbml/cbmlv3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="case">
		<xs:complexType>
			<xs:choice>
				<xs:element name="structure" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="feature" maxOccurs="unbounded" type="structure_feature"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>	
				<xs:element name="similarity" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="feature" minOccurs="0" maxOccurs="unbounded" type="similarity_feature"/>
						</xs:sequence>
						<xs:attribute name="username" type="xs:ID" use="required"/>
						<xs:attribute name="extends" type="xs:IDREF" use="optional"/>
					</xs:complexType>
				</xs:element>				
			</xs:choice>
			<xs:attribute name="domain" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>	
			
	<xs:complexType name="similarity_feature">
		<xs:choice>
			<xs:element name="feature" minOccurs="1" maxOccurs="unbounded" type="similarity_feature"/>			
			<xs:element name="array" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="primary" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="secondary" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required"/>
											<xs:attribute name="similarity" type="xs:double" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="name" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="graph"  minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="point" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="difference" type="xs:double" use="required"/>
								<xs:attribute name="similarity" type="xs:double" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>	
					<xs:attribute name="type" type="graphType" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="measure" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="exact" minOccurs="1" maxOccurs="1"/>			
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="weight" type="positiveDouble" use="required"/>	
	</xs:complexType>
	
	<xs:simpleType name="positiveDouble">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
		
	<xs:simpleType name="normalisedDouble">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="graphType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="symmetrical"/>
			<xs:enumeration value="asymmetrical"/>
		</xs:restriction>
	</xs:simpleType>	
	
	<xs:complexType name="structure_feature">
		<xs:choice>
			<xs:element name="complex">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="feature" minOccurs="0" maxOccurs="unbounded" type="structure_feature"/>
					</xs:sequence>
					<xs:attributeGroup ref="references"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="symbol">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="enumeration" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attributeGroup ref="references"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="string">
				<xs:complexType>
					<xs:attributeGroup ref="references"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="taxonomy">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="node" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attributeGroup ref="references"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="integer">
				<xs:complexType>
					<xs:all>
						<xs:element name="maxInclusive" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="value" type="xs:int" use="required"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="minInclusive" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="value" type="xs:int" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:all>
					<xs:attributeGroup ref="references"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="double">
				<xs:complexType>
					<xs:all>
						<xs:element name="maxInclusive" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="value" type="xs:double" use="required"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="minInclusive" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="value" type="xs:double" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:all>
					<xs:attributeGroup ref="references"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="boolean">
				<xs:complexType>
					<xs:attributeGroup ref="references"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="discriminant" use="optional" default="true" type="xs:boolean"/>
		<xs:attribute name="solution"     use="optional" default="false" type="xs:boolean"/>
		<xs:attribute name="manditory"    use="optional" default="true" type="xs:boolean"/>
	</xs:complexType>

	<xs:attributeGroup name="references">
		<xs:attribute name="name" type="xs:ID" use="optional"/>
		<xs:attribute name="ref" type="xs:IDREF" use="optional"/>
	</xs:attributeGroup>
	<xs:element name="enumeration">
		<xs:complexType>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="node">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="node" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== knoxsp/Concept/cbml/structurewithflatsituations.xml
<?xml version="1.0" encoding="UTF-8"?>
<case domain="pta.offer" xsi:noNamespaceSchemaLocation="/home/pta/xml/cbmlv3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<structure>
	
		<feature name="location" manditory="false">
			<taxonomy name="Places">
				<node name="NotInUCD">
					<node name="home"/>
				</node>
				<node name="CASL">
					<node name="CASLThirdFloor">
						<node name="CASLThirdFloorCubeF">
							<node name="KnoxDesk"/>
							<node name="LorcanDesk"/>
							<node name="AdoDesk"/>				
						</node>
						<node name="CASLThirdFloorCubeG">
							<node name="GraemeDesk"/>
							<node name="GrahamDesk"/>				
						</node>
						<node name="ThirdFloorFoyer"/>
						<node name="simonOffice"/>
						<node name="ThirdFloorCorridor"/>
						<node name="aaronOffice"/>
						<node name="paddyOffice"/>
						<node name="joeOffice"/>
						<node name="lukeOffice"/>
						<node name = "internArea"/>
					</node>
					<node name="CASLFourthFloor">
						<node name="FourthFloorFoyer">
						<node name="CASLFourthFloorCommonArea"/>
							<node name="CASLCommonRoomComfySeatingArea"/>
							<node name="RocketFoods"/>
							<node name="EatingArea"/>
						</node>
					</node>
				</node>
			</taxonomy>
		</feature>	
		
		<feature name="locationothers" manditory="false">
			<taxonomy ref="Places"/>
		</feature>
		<feature name="time" manditory="false">
			<symbol>
				<enumeration value="weekend"/>
				<enumeration value="0900-0930"/>
				<enumeration value="0930-1000"/>
				<enumeration value="1000-1030"/>
				<enumeration value="1030-1100"/>
				<enumeration value="1100-1130"/>
				<enumeration value="1130-1200"/>
				<enumeration value="1200-1230"/>
				<enumeration value="1230-1300"/>
				<enumeration value="1300-1330"/>
				<enumeration value="1330-1400"/>
				<enumeration value="1400-1430"/>
				<enumeration value="1430-1500"/>
				<enumeration value="1500-1530"/>
				<enumeration value="1530-1600"/>
				<enumeration value="1600-1630"/>
				<enumeration value="1630-1700"/>
				<enumeration value="notworktime"/>
			</symbol>
		</feature>
		
		<feature name="calendar" manditory="false">
			<symbol>
				<enumeration value="break"/>
				<enumeration value="meeting"/>
				<enumeration value="coffee"/>
				<enumeration value="lunch"/>
			</symbol>
		</feature>	
		
		<feature name="IM" manditory="false">
			<symbol>
				<enumeration value="available"/>
				<enumeration value="idle"/>
				<enumeration value="away"/>
				<enumeration value="dnd"/>
			</symbol>
		</feature>	
		
		<feature name="situation" discriminant="false" solution="true" manditory="false">
			<symbol>
				<enumeration value="activeatcomputer"/>
				<enumeration value="break"/>
				<enumeration value="meeting"/>
				<enumeration value="coffee"/>
				<enumeration value="lunch"/>
				<enumeration value="atwork"/>
				<enumeration value="notatwork"/>
				<enumeration value="atdesk"/>
				<enumeration value="procrastinating"/>
				<enumeration value="gonehome"/>
				<enumeration value="toilet"/>
			</symbol>
		</feature>
		
		<feature name="activity" manditory="true">
			<symbol>
				<enumeration value="tenseconds"/>
				<enumeration value="minute"/>
				<enumeration value="hour"/>
				<enumeration value="overhour"/>
			</symbol>
		</feature>	
		</structure>
</case>

=== knoxsp/Concept/cbml/kasterensimilarity.xml
<?xml version="1.0" encoding="UTF-8"?>
<case domain="scatterbox" xsi:noNamespaceSchemaLocation="/home/pta/xml/cbmlv3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	
<similarity username="default">
		<feature name="situation" weight="1">
			<measure name="scatterbox.similarity.SituationSimilarityMeasure"/>
		</feature>
		<feature name="time" weight="1">
			<exact/>
		</feature>
			<feature name="hallbedroomdoor" weight="1">
			<exact/>
		</feature>
		
		<feature name="halltoiletdoor" weight="1">
			<exact/>
		</feature>
		
		<feature name="hallbathroomdoor" weight="1">
			<exact/>
		</feature>
		
		<feature name="toiletflush" weight="1">
			<exact/>
		</feature>
		
		<feature name="platescupboard" weight="1">
			<exact/>
		</feature>
		
		<feature name="fridge" weight="1">
			<exact/>
		</feature>
		
		<feature name="microwave" weight="1">
			<exact/>
		</feature>
		
		<feature name="groceriescupboard" weight="1">
			<exact/>
		</feature>
		
		<feature name="dishwasher" weight="1">
			<exact/>
		</feature>
		
		<feature name="panscupboard" weight="1">
			<exact/>
		</feature>
		
		<feature name="cupscupboard" weight="1">
			<exact/>
		</feature>
		
		<feature name="frontdoor" weight="1">
			<exact/>
		</feature>
		
		<feature name="freezer" weight="1">
			<exact/>
		</feature>
		
		<feature name="washingmachine" weight="1">
			<exact/>
		</feature>
		

	</similarity>
	<!--<similarity username="coylel" extends="default"/>
	<similarity username="joebloggs" extends="default"/>
	-->
</case>

=== knoxsp/Concept/cbml/caslstructure.xml
<?xml version="1.0" encoding="UTF-8"?>
<case domain="pta.offer" xsi:noNamespaceSchemaLocation="/home/pta/xml/cbmlv3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<structure>
	
		<feature name="location" manditory="false">
			<taxonomy name="Places">
				<node name="NotInUCD">
					<node name="home"/>
				</node>
				<node name="CASL">
					<node name="CASLThirdFloor">
						<node name="CASLThirdFloorCubeF">
							<node name="KnoxDesk"/>
							<node name="LorcanDesk"/>
							<node name="AdoDesk"/>				
						</node>
						<node name="CASLThirdFloorCubeG">
							<node name="GraemeDesk"/>
							<node name="GrahamDesk"/>				
						</node>
						<node name="ThirdFloorFoyer"/>
						<node name="simonOffice"/>
						<node name="ThirdFloorCorridor"/>
						<node name="aaronOffice"/>
						<node name="paddyOffice"/>
						<node name="joeOffice"/>
						<node name="lukeOffice"/>
						<node name = "internArea"/>
					</node>
					<node name="CASLFourthFloor">
						<node name="FourthFloorFoyer">
						<node name="CASLFourthFloorCommonArea"/>
							<node name="CASLCommonRoomComfySeatingArea"/>
							<node name="RocketFoods"/>
							<node name="EatingArea"/>
						</node>
					</node>
				</node>
			</taxonomy>
		</feature>	
		
		<feature name="situation" discriminant="false" solution="true" manditory="false">
			<taxonomy name="situations">
			<node name="default"/>
			   <node name="atwork">
				   <node name="break">
					   <node name="coffee"/>
					   <node name="lunch"/>
				   </node>
				   <node name="toilet"/>
				   <node name="atdesk">
				       <node name="activeatcomputer"/>
				   </node>
				   <node name="meeting"/>
				   <node name="procrastinating"/>
			   </node>
			   <node name="notatwork">
				   <node name="gonehome"/>
			   </node>
			</taxonomy>
		</feature>
		
		<feature name="locationothers" manditory="false">
			<taxonomy ref="Places"/>
		</feature>
		<feature name="time" manditory="false">
			<symbol>
				<enumeration value="weekend"/>
				<enumeration value="830-900"/>
				<enumeration value="900-930"/>
				<enumeration value="930-1000"/>
				<enumeration value="1000-1030"/>
				<enumeration value="1030-1100"/>
				<enumeration value="1100-1130"/>
				<enumeration value="1130-1200"/>
				<enumeration value="1200-1230"/>
				<enumeration value="1230-1300"/>
				<enumeration value="1300-1330"/>
				<enumeration value="1330-1400"/>
				<enumeration value="1400-1430"/>
				<enumeration value="1430-1500"/>
				<enumeration value="1500-1530"/>
				<enumeration value="1530-1600"/>
				<enumeration value="1600-1630"/>
				<enumeration value="1630-1700"/>
				<enumeration value="1700-1730"/>
				<enumeration value="1730-1800"/>
				<enumeration value="1800-1830"/>
				<enumeration value="1830-1900"/>
			</symbol>
		</feature>
		
		<feature name="calendar" manditory="false">
			<symbol>
				<enumeration value="break"/>
				<enumeration value="meeting"/>
				<enumeration value="coffee"/>
				<enumeration value="lunch"/>
				<enumeration value="busy"/>
			</symbol>
		</feature>	
		
		<feature name="IM" manditory="false">
			<symbol>
				<enumeration value="available"/>
				<enumeration value="idle"/>
				<enumeration value="away"/>
				<enumeration value="dnd"/>
			</symbol>
		</feature>	
		
		<feature name="activity" manditory="false">
			<symbol>
				<enumeration value="tenseconds"/>
				<enumeration value="minute"/>
				<enumeration value="hour"/>
				<enumeration value="overhour"/>
			</symbol>
		</feature>	
		
		</structure>
</case>

=== knoxsp/Concept/cbml/kasterenstructure.xml
<?xml version="1.0" encoding="UTF-8"?>
<case domain="pta.offer" xsi:noNamespaceSchemaLocation="/home/pta/xml/cbmlv3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<structure>
	
		<feature name="situation" discriminant="false" solution="true" manditory="false">
			<taxonomy name="situations">
						<node name="default"/>
					   <node name="gotobed"/>
					   <node name="usetoilet"/>
					   <node name="preparebreakfast"/>
					   <node name="takeshower"/>
					   <node name="leavehouse"/>
					   <node name="getdrink"/>
					   <node name="preparedinner"/>
			</taxonomy>
		</feature>
		
		<feature name="time" manditory="false">
			<symbol>
				<enumeration value="800-830"/>
				<enumeration value="830-900"/>
				<enumeration value="900-930"/>
				<enumeration value="930-1000"/>
				<enumeration value="1000-1030"/>
				<enumeration value="1030-1100"/>
				<enumeration value="1100-1130"/>
				<enumeration value="1130-1200"/>
				<enumeration value="1200-1230"/>
				<enumeration value="1230-1300"/>
				<enumeration value="1300-1330"/>
				<enumeration value="1330-1400"/>
				<enumeration value="1400-1430"/>
				<enumeration value="1430-1500"/>
				<enumeration value="1500-1530"/>
				<enumeration value="1530-1600"/>
				<enumeration value="1600-1630"/>
				<enumeration value="1630-1700"/>
				<enumeration value="1700-1730"/>
				<enumeration value="1730-1800"/>
				<enumeration value="1800-1830"/>
				<enumeration value="1830-1900"/>
				<enumeration value="1900-1930"/>
				<enumeration value="1930-2000"/>
				<enumeration value="2000-2030"/>
				<enumeration value="2030-2100"/>
				<enumeration value="2100-2130"/>
				<enumeration value="2130-2200"/>
				<enumeration value="2200-2230"/>
				<enumeration value="2230-2300"/>
				<enumeration value="2300-2330"/>
				<enumeration value="2330-2400"/>
			</symbol>
		</feature>
		
		
		<feature name="hallbedroomdoor" manditory="false">
			<string/>
		</feature>
		
		<feature name="halltoiletdoor" manditory="false">
			<string/>
		</feature>
		
		<feature name="hallbathroomdoor" manditory="false">
			<string/>
		</feature>
		
		<feature name="toiletflush" manditory="false">
			<string/>
		</feature>
		
		<feature name="platescupboard" manditory="false">
			<string/>
		</feature>
		
		<feature name="fridge" manditory="false">
			<string/>
		</feature>
		
		<feature name="microwave" manditory="false">
			<string/>
		</feature>
		
		<feature name="groceriescupboard" manditory="false">
			<string/>
		</feature>
		
		<feature name="dishwasher" manditory="false">
			<string/>
		</feature>
		
		<feature name="panscupboard" manditory="false">
			<string/>
		</feature>
		
		<feature name="cupscupboard" manditory="false">
			<string/>
		</feature>
		
		<feature name="frontdoor" manditory="false">
			<string/>
		</feature>
		
		<feature name="freezer" manditory="false">
			<string/>
		</feature>
		
		<feature name="washingmachine" manditory="false">
			<string/>
		</feature>
		
		</structure>
</case>
